"""create company_settings table

Revision ID: 4a625b86562b
Revises: fix_ticket_defaults
Create Date: 2026-05-31 16:58:09.763295
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a625b86562b'
down_revision = 'fix_ticket_defaults'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_opened_company_id'), table_name='ticket_opened')
    op.drop_index(op.f('ix_ticket_opened_id'), table_name='ticket_opened')
    op.drop_index(op.f('ix_ticket_opened_ticket_id'), table_name='ticket_opened')
    op.drop_table('ticket_opened')
    op.drop_index(op.f('ix_ticket_company_id'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_id'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('issue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', postgresql.ENUM('payment', 'technical', 'general', name='ticketcategory'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'closed', name='ticketstatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('ticket_company_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_pkey'))
    )
    op.create_index(op.f('ix_ticket_id'), 'ticket', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_company_id'), 'ticket', ['company_id'], unique=False)
    op.create_table('ticket_opened',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('opened_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], name=op.f('ticket_opened_company_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('ticket_opened_ticket_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ticket_opened_pkey'))
    )
    op.create_index(op.f('ix_ticket_opened_ticket_id'), 'ticket_opened', ['ticket_id'], unique=False)
    op.create_index(op.f('ix_ticket_opened_id'), 'ticket_opened', ['id'], unique=False)
    op.create_index(op.f('ix_ticket_opened_company_id'), 'ticket_opened', ['company_id'], unique=False)
    # ### end Alembic commands ###
