"""create ticket tables

Revision ID: 886ccfbe74e8
Revises: f920af34db03
Create Date: 2026-05-31 16:07:49.117741
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886ccfbe74e8'
down_revision = 'f920af34db03'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
