"""add company_model_name to company_finetune

Revision ID: f920af34db03
Revises: 0002
Create Date: 2026-05-22 23:37:34.776900
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f920af34db03'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    
    # Add company_model_name with default value for existing records
    op.add_column('company_finetune', sa.Column('company_model_name', sa.String(length=255), nullable=True))
    
    # Update existing rows with model names based on company names
    op.execute("""
        UPDATE company_finetune cf
        SET company_model_name = 'perai-' || LOWER(REPLACE(c.company_name, ' ', '-'))
        FROM company c
        WHERE cf.company_id = c.id
    """)
    
    # Now make the column NOT NULL
    op.alter_column('company_finetune', 'company_model_name', nullable=False)
    op.create_index(op.f('ix_company_finetune_company_model_name'), 'company_finetune', ['company_model_name'], unique=False)
    op.create_index(op.f('ix_company_finetune_id'), 'company_finetune', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_finetune_id'), table_name='company_finetune')
    op.drop_index(op.f('ix_company_finetune_company_model_name'), table_name='company_finetune')
    op.drop_column('company_finetune', 'company_model_name')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=False)
    # ### end Alembic commands ###
